name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: List directory before running script
      run: Get-ChildItem -Path . -Recurse
      shell: pwsh

    - name: Run remote build script
      run: ./remote_build.ps1
      shell: pwsh

    - name: List directory after running script
      run: Get-ChildItem -Path . -Recurse
      shell: pwsh
