name: Deploy to GitHub every 5 minutes

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    if: github.repository == 'manu-180/ultima_prueba'
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Git
        run: |
          git config --local user.email "manunv97@gmail.com"
          git config --local user.name "Manuel"

      - name: Add changes to Git
        run: |
          git add .

      - name: Check for changes and commit
        run: |
          git commit -m "cambios"
        - name: haciendo push
        run: |
          git push
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update static build
          commit_user_name: Manuel Navarro [GitHub Actions]
          commit_user_email: manunv97@gmail.com
          commit_author: manunv <manunv97@gmail.com>
