name: Deploy to GitHub every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Ejecutar cada 5 minutos

jobs:
  deploy:
    runs-on: windows-latest  # Usar el último sistema operativo Windows disponible

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Esta acción permite clonar el repositorio

      - name: Set up Git
        run: |
          git config --local user.email "manunv97@gmail.com"
          git config --local user.name "Manuel"

      - name: Add changes to git
        run: |
          echo "Adding changes to git"
          git add .

      - name: Commit changes
        run: |
          echo "Committing changes"
          git commit -m "Committing changes from GitHub Actions"

      - name: Push changes to GitHub
        run: |
          echo "Pushing changes"
          git push origin HEAD:main  # Cambia 'main' por tu rama principal si es diferente
