name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up Git user
      run: |
        git config --global user.email "manunv97@gmail.com"
        git config --global user.name "Manuel"
      shell: pwsh

    - name: List directory before running script
      run: Get-ChildItem -Path . -Recurse
      shell: pwsh

    - name: Run remote build script
      run: ./remote_build.ps1
      shell: pwsh

    - name: List directory after running script
      run: Get-ChildItem -Path . -Recurse
      shell: pwsh

    - name: Push changes to repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add .
        git commit -m "Adjust workflow for Windows environment"
        git push
      shell: pwsh
